openapi: 3.0.3
info:
  title: KomMonitor Timeseries Data Access API
  description: "Definition einer Datenzugriffs-API, die den Zugriff auf die KomMonitor-Timeseries Daten kapselt."
  contact:
    email: b.pross@52north.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
  - url: //localhost:8080/
tags:
  - name: access-control
    description: the AccessControl API
  - name: database-public
    description: the public Database API
paths:
  /stations:
    post:
      tags:
        - stations
      summary: Add a new station
      description: Add/Register a station
      operationId: addStationAsBody
      requestBody:
        description: station data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StationMetadata'
        required: true
      responses:
        "201":
          description: Created
        "204":
          description: No content
        "401":
          description: API key is missing or invalid
          content: {}
        "403":
          description: Forbidden
          content: {}
        "404":
          description: Not Found
          content: {}
        "405":
          description: Invalid input
          content: {}
    get:
      tags:
        - stations
      summary: Get stations
      description: Get stations
      operationId: getStations
      responses:
        "200":
          description: station data
          content:
            application/json:
              schema:
                type: array
                items:
                   $ref: '#/components/schemas/StationMetadata'
        "401":
            description: API key is missing or invalid
            content: {}
        "403":
          description: Forbidden
          content: {}
        "404":
          description: Not Found
          content: {}
        "405":
          description: Invalid input
          content: {}
  /timeseries:
    post:
      tags:
        - timeseries
      summary: Add timeseries metadata
      description: Add timeseries metadata
      operationId: addTimeseriesMetadataAsBody
      requestBody:
        description: timeseries metadata
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimeseriesMetadata'
        required: true
      responses:
        "201":
          description: Created
        "401":
          description: API key is missing or invalid
          content: {}
        "403":
          description: Forbidden
          content: {}
        "404":
          description: Not Found
          content: {}
        "405":
          description: Invalid input
          content: {}
  /timeseries/{stationId}/{parameterId}:
    post:
      tags:
        - timeseries
      summary: Add timeseries data
      description: Add timeseries data
      operationId: addTimeseriesAsBody
      parameters:
        - name: stationId
          in: path
          description: the identifier of the station
          required: true
          schema:
            type: number
        - name: parameterId
          in: path
          description: the identifier of the parameter
          required: true
          schema:
            type: number
      requestBody:
        description: timeseries data
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/TimeseriesData'
        required: true
      responses:
        "201":
          description: Created
        "401":
          description: API key is missing or invalid
          content: {}
        "403":
          description: Forbidden
          content: {}
        "404":
          description: Not Found
          content: {}
        "405":
          description: Invalid input
          content: {}    
    get:
      tags:
        - timeseries
      summary: Get timeseries data
      description: Get timeseries data
      operationId: getTimeseries
      parameters:
        - name: stationId
          in: path
          description: the identifier of the station
          required: true
          schema:
            type: number
        - name: parameterId
          in: path
          description: the identifier of the parameter
          required: true
          schema:
            type: number
      responses:
        "200":
          description: timeseries data
          content:
            application/json:
              schema:
                type: array
                items:
                   $ref: '#/components/schemas/TimeseriesData'
        "401":
            description: API key is missing or invalid
            content: {}
        "403":
          description: Forbidden
          content: {}
        "404":
          description: Not Found
          content: {}
        "405":
          description: Invalid input
          content: {}
  /timeseries/{stationId}:
    post:
      tags:
        - timeseriesWithParameterName
      summary: Add timeseries data with parameter name
      description: Add timeseries data with parameter name
      operationId: addTimeseriesAsWithParameterNameBody
      parameters:
        - name: stationId
          in: path
          description: the identifier of the station
          required: true
          schema:
            type: number
      requestBody:
        description: timeseries data with parameter name
        content:
          application/json:
            schema:
               $ref: '#/components/schemas/TimeseriesDataWithParameterName'
        required: true
      responses:
        "201":
          description: Created
        "401":
          description: API key is missing or invalid
          content: {}
        "403":
          description: Forbidden
          content: {}
        "404":
          description: Not Found
          content: {}
        "405":
          description: Invalid input
          content: {}
  /timeseries/{stationId}/{parameterId}/aggregates:
    get:
      tags:
        - aggregates
      summary: Get timeseries aggregates
      description: Get timeseries aggregates
      operationId: getTimeseriesAggregates
      parameters:
        - name: stationId
          in: path
          description: the identifier of the station
          required: true
          schema:
            type: number
        - name: parameterId
          in: path
          description: the identifier of the parameter
          required: true
          schema:
            type: number
        - name: frequency
          in: query
          description: the identifier of the station
          required: true
          schema:
            type: string
        - name: function
          in: query
          description: the identifier of the parameter
          required: true
          schema:
            type: string
      responses:
        "200":
          description: aggregated timeseries data
          content:
            application/json:
              schema:
                type: array
                items:
                   $ref: '#/components/schemas/TimeseriesAggregateData'
        "401":
            description: API key is missing or invalid
            content: {}
        "403":
          description: Forbidden
          content: {}
        "404":
          description: Not Found
          content: {}
        "405":
          description: Invalid input
          content: {}
components:
    schemas:
        StationMetadata:
          title: StationMetadata
          required:
            - name
            - id
            - position
            - parameters
          type: object
          properties:
            name:
              type: string
              description: the name of the station
            id:
              type: number
              description: the id of the station
            position:
              $ref: '#/components/schemas/Position'
              description: information about the position of the station
            parameters:
              type: array
              items:
                $ref: '#/components/schemas/Parameter'
              description: list of parameters of the station
        Position:
            title: Position
            required:
                - x
                - y
            type: object
            properties:
                x:
                 type: number
                y:
                 type: number
        Parameter:
            title: Parameter
            required:
                - name
                - unit
            type: object
            properties:
                id:
                 type: number
                name:
                 type: string
                unit:
                 type: string
        TimeseriesData:
            title: TimeseriesData
            required:
                - value
                - timestamp
            type: object
            properties:
                value: 
                  type: number
                  format: float
                timestamp:
                  type: date-time
        TimeseriesAggregateData:
            title: TimeseriesAggregateData
            type: object
            properties:
              time-bucket:
                type: date-time
            required:
              - time-bucket
            additionalProperties:
                type: number
                format: float
        TimeseriesMetadata:
            title: Timeseries
            required:
                - station_id
                - parameter
            type: object
            properties:
                station_id:
                  type: number
                parameter:
                  $ref: '#/components/schemas/Parameter'
        TimeseriesDataWithParameterName:
            title: TimeseriesDataWithParameterName
            type: object
            properties:
              parameter_name:
                type: string
              timeseries:
                type: array
                items:
                  $ref: '#/components/schemas/TimeseriesData'                
            required:
              - parameter_name
              - timeseries  