/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package de.hsbo.kommonitor.timeseries_management.api;

import java.math.BigDecimal;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import de.hsbo.kommonitor.timeseries_management.model.TimeseriesAggregateDataValue;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-29T14:02:55.548290400+01:00[Europe/Berlin]", comments = "Generator version: 7.13.0")
@Validated
@Tag(name = "aggregates", description = "the aggregates API")
public interface AggregatesApi {

    /**
     * GET /timeseries/{stationId}/{parameterId}/aggregates : Get timeseries aggregates
     * Get timeseries aggregates
     *
     * @param stationId the identifier of the station (required)
     * @param parameterId the identifier of the parameter (required)
     * @param frequency the identifier of the station (required)
     * @param function the identifier of the parameter (required)
     * @return timeseries data (status code 200)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Invalid input (status code 405)
     */
    @Operation(
        operationId = "getTimeseriesAggregates",
        summary = "Get timeseries aggregates",
        description = "Get timeseries aggregates",
        tags = { "aggregates" },
        responses = {
            @ApiResponse(responseCode = "200", description = "timeseries data", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = TimeseriesAggregateDataValue.class)))
            }),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found"),
            @ApiResponse(responseCode = "405", description = "Invalid input")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/timeseries/{stationId}/{parameterId}/aggregates",
        produces = { "application/json" }
    )
    
    ResponseEntity<?> getTimeseriesAggregates(
        @Parameter(name = "stationId", description = "the identifier of the station", required = true, in = ParameterIn.PATH) @PathVariable("stationId") BigDecimal stationId,
        @Parameter(name = "parameterId", description = "the identifier of the parameter", required = true, in = ParameterIn.PATH) @PathVariable("parameterId") BigDecimal parameterId,
        @NotNull @Parameter(name = "frequency", description = "the identifier of the station", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "frequency", required = true) String frequency,
        @NotNull @Parameter(name = "function", description = "the identifier of the parameter", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "function", required = true) String function
    );

}
