/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package de.hsbo.kommonitor.timeseries_management.api;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import de.hsbo.kommonitor.timeseries_management.model.StationMetadata;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-28T08:53:57.253276600+01:00[Europe/Berlin]", comments = "Generator version: 7.13.0")
@Validated
@Tag(name = "stations", description = "the stations API")
public interface StationsApi {

    /**
     * POST /stations : Add a new station
     * Add/Register a station
     *
     * @param stationMetadata station data (required)
     * @return Created (status code 201)
     *         or No content (status code 204)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Invalid input (status code 405)
     */
    @Operation(
        operationId = "addStationAsBody",
        summary = "Add a new station",
        description = "Add/Register a station",
        tags = { "stations" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created"),
            @ApiResponse(responseCode = "204", description = "No content"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found"),
            @ApiResponse(responseCode = "405", description = "Invalid input")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/stations",
        consumes = { "application/json" }
    )
    
    ResponseEntity<?> addStationAsBody(
        @Parameter(name = "StationMetadata", description = "station data", required = true) @Valid @RequestBody StationMetadata stationMetadata
    );


    /**
     * GET /stations : Get stations
     * Get stations
     *
     * @return station data (status code 200)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Invalid input (status code 405)
     */
    @Operation(
        operationId = "getStations",
        summary = "Get stations",
        description = "Get stations",
        tags = { "stations" },
        responses = {
            @ApiResponse(responseCode = "200", description = "station data", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = StationMetadata.class)))
            }),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found"),
            @ApiResponse(responseCode = "405", description = "Invalid input")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/stations",
        produces = { "application/json" }
    )
    
    ResponseEntity<?> getStations(
        
    );

}
