/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package de.hsbo.kommonitor.timeseries_management.api;

import java.math.BigDecimal;
import de.hsbo.kommonitor.timeseries_management.model.Timeseries;
import de.hsbo.kommonitor.timeseries_management.model.TimeseriesMetadata;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-03T11:14:26.096035+01:00[Europe/Berlin]", comments = "Generator version: 7.13.0")
@Validated
@Tag(name = "timeseries", description = "the timeseries API")
public interface TimeseriesApi {

    /**
     * POST /timeseries/{stationId}/{parameterId} : Add timeseries data
     * Add timeseries data
     *
     * @param stationId the identifier of the station (required)
     * @param parameterId the identifier of the parameter (required)
     * @param timeseries timeseries data (required)
     * @return Created (status code 201)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Invalid input (status code 405)
     */
    @Operation(
        operationId = "addTimeseriesAsBody",
        summary = "Add timeseries data",
        description = "Add timeseries data",
        tags = { "timeseries" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found"),
            @ApiResponse(responseCode = "405", description = "Invalid input")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/timeseries/{stationId}/{parameterId}",
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> addTimeseriesAsBody(
        @Parameter(name = "stationId", description = "the identifier of the station", required = true, in = ParameterIn.PATH) @PathVariable("stationId") BigDecimal stationId,
        @Parameter(name = "parameterId", description = "the identifier of the parameter", required = true, in = ParameterIn.PATH) @PathVariable("parameterId") BigDecimal parameterId,
        @Parameter(name = "Timeseries", description = "timeseries data", required = true) @Valid @RequestBody Timeseries timeseries
    );


    /**
     * POST /timeseries : Add timeseries metadata
     * Add timeseries metadata
     *
     * @param timeseriesMetadata timeseries metadata (required)
     * @return Created (status code 201)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Invalid input (status code 405)
     */
    @Operation(
        operationId = "addTimeseriesMetadataAsBody",
        summary = "Add timeseries metadata",
        description = "Add timeseries metadata",
        tags = { "timeseries" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found"),
            @ApiResponse(responseCode = "405", description = "Invalid input")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/timeseries",
        consumes = { "application/json" }
    )
    
    ResponseEntity<?> addTimeseriesMetadataAsBody(
        @Parameter(name = "TimeseriesMetadata", description = "timeseries metadata", required = true) @Valid @RequestBody TimeseriesMetadata timeseriesMetadata
    );


    /**
     * GET /timeseries/{stationId}/{parameterId} : Get timeseries data
     * Get timeseries data
     *
     * @param stationId the identifier of the station (required)
     * @param parameterId the identifier of the parameter (required)
     * @return timeseries data (status code 200)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Invalid input (status code 405)
     */
    @Operation(
        operationId = "getTimeseries",
        summary = "Get timeseries data",
        description = "Get timeseries data",
        tags = { "timeseries" },
        responses = {
            @ApiResponse(responseCode = "200", description = "timeseries data", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Timeseries.class)))
            }),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found"),
            @ApiResponse(responseCode = "405", description = "Invalid input")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/timeseries/{stationId}/{parameterId}",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<Timeseries>> getTimeseries(
        @Parameter(name = "stationId", description = "the identifier of the station", required = true, in = ParameterIn.PATH) @PathVariable("stationId") BigDecimal stationId,
        @Parameter(name = "parameterId", description = "the identifier of the parameter", required = true, in = ParameterIn.PATH) @PathVariable("parameterId") BigDecimal parameterId
    );

}
