/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package de.hsbo.kommonitor.timeseries_management.api;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.List;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import de.hsbo.kommonitor.timeseries_management.model.TimeseriesData;
import de.hsbo.kommonitor.timeseries_management.model.TimeseriesMetadata;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-02-23T13:15:22.249674500+01:00[Europe/Berlin]", comments = "Generator version: 7.13.0")
@Validated
@Tag(name = "timeseries", description = "the timeseries API")
public interface TimeseriesApi {

    /**
     * POST /timeseries/{stationId}/{parameterId} : Add timeseries data
     * Add timeseries data
     *
     * @param stationId the identifier of the station (required)
     * @param parameterId the identifier of the parameter (required)
     * @param timeseriesData timeseries data (required)
     * @return Created (status code 201)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Invalid input (status code 405)
     */
    @Operation(
        operationId = "addTimeseriesAsBody",
        summary = "Add timeseries data",
        description = "Add timeseries data",
        tags = { "timeseries" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found"),
            @ApiResponse(responseCode = "405", description = "Invalid input")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/timeseries/{stationId}/{parameterId}",
        consumes = { "application/json" }
    )
    
    ResponseEntity<?> addTimeseriesAsBody(
        @Parameter(name = "stationId", description = "the identifier of the station", required = true, in = ParameterIn.PATH) @PathVariable("stationId") BigDecimal stationId,
        @Parameter(name = "parameterId", description = "the identifier of the parameter", required = true, in = ParameterIn.PATH) @PathVariable("parameterId") BigDecimal parameterId,
        @Parameter(name = "TimeseriesData", description = "timeseries data", required = true) @Valid @RequestBody List<@Valid TimeseriesData> timeseriesData
    );


    /**
     * POST /timeseries : Add timeseries metadata
     * Add timeseries metadata
     *
     * @param timeseriesMetadata timeseries metadata (required)
     * @return Created (status code 201)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Invalid input (status code 405)
     */
    @Operation(
        operationId = "addTimeseriesMetadataAsBody",
        summary = "Add timeseries metadata",
        description = "Add timeseries metadata",
        tags = { "timeseries" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created"),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found"),
            @ApiResponse(responseCode = "405", description = "Invalid input")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/timeseries",
        consumes = { "application/json" }
    )
    
    ResponseEntity<?> addTimeseriesMetadataAsBody(
        @Parameter(name = "TimeseriesMetadata", description = "timeseries metadata", required = true) @Valid @RequestBody TimeseriesMetadata timeseriesMetadata
    );


    /**
     * GET /timeseries/{stationId}/{parameterId} : Get timeseries data
     * Get timeseries data
     *
     * @param stationId the identifier of the station (required)
     * @param parameterId the identifier of the parameter (required)
     * @param start optional start timestamp (optional)
     * @param end optional end timestamp (optional)
     * @return timeseries data (status code 200)
     *         or API key is missing or invalid (status code 401)
     *         or Forbidden (status code 403)
     *         or Not Found (status code 404)
     *         or Invalid input (status code 405)
     */
    @Operation(
        operationId = "getTimeseries",
        summary = "Get timeseries data",
        description = "Get timeseries data",
        tags = { "timeseries" },
        responses = {
            @ApiResponse(responseCode = "200", description = "timeseries data", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = TimeseriesData.class)))
            }),
            @ApiResponse(responseCode = "401", description = "API key is missing or invalid"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not Found"),
            @ApiResponse(responseCode = "405", description = "Invalid input")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/timeseries/{stationId}/{parameterId}",
        produces = { "application/json" }
    )
    
    ResponseEntity<?> getTimeseries(
        @Parameter(name = "stationId", description = "the identifier of the station", required = true, in = ParameterIn.PATH) @PathVariable("stationId") BigDecimal stationId,
        @Parameter(name = "parameterId", description = "the identifier of the parameter", required = true, in = ParameterIn.PATH) @PathVariable("parameterId") BigDecimal parameterId,
        @Parameter(name = "start", description = "optional start timestamp", in = ParameterIn.QUERY) @Valid @RequestParam(value = "start", required = false) OffsetDateTime start,
        @Parameter(name = "end", description = "optional end timestamp", in = ParameterIn.QUERY) @Valid @RequestParam(value = "end", required = false) OffsetDateTime end
    );

}
